<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.yzc</groupId>
        <artifactId>yzc_deposit</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <groupId>com.yzc.deposit</groupId>
    <artifactId>deposit_web</artifactId>
    <version>1.0-SNAPSHOT</version>
    <dependencies>
        <dependency>
            <groupId>com.yzc.deposit</groupId>
            <artifactId>deposit_controller</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <!-- 注册中心 -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>

        <!-- 配置中心 -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <dependency>
            <groupId>org.jsoup</groupId>
            <artifactId>jsoup</artifactId>
            <version>1.13.1</version>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>2.7.2</version>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
        <!--设置.jks不被编译，为什么写两种方式 暂时不清楚 -->
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
                <excludes>
                    <exclude>**/*.xml</exclude>
                    <exclude>**/*.doc</exclude>
                    <exclude>**/*.docx</exclude>
                    <exclude>**/*.xlsx</exclude>
                    <exclude>**/*.ftl</exclude>
                    <exclude>**/*.jks</exclude>
                </excludes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
                <includes>
                    <include>**/*.xml</include>
                    <include>**/*.doc</include>
                    <include>**/*.docx</include>
                    <include>**/*.xlsx</include>
                    <include>**/*.ftl</include>
                    <include>**/*.jks</include>
                </includes>
            </resource>
        </resources>
    </build>
    <profiles>
        <!-- 平台版本 -->
        <profile>
            <id>yzc</id>
            <properties>
                <profile.active>yzc</profile.active>
            </properties>
            <dependencies>
                <dependency>
                    <groupId>com.yzc</groupId>
                    <artifactId>common-api-yzc-impl</artifactId>
                    <version>1.0-SNAPSHOT</version>
                </dependency>
                <dependency>
                    <groupId>com.yzc</groupId>
                    <artifactId>common-global</artifactId>
                    <version>1.0-SNAPSHOT</version>
                </dependency>
            </dependencies>
        </profile>
        <!-- 新华印刷部署版本 -->
        <profile>
            <id>xhys</id>
            <properties>
                <profile.active>xhys</profile.active>
            </properties>
            <dependencies>
                <dependency>
                    <groupId>com.yzc</groupId>
                    <artifactId>common-api-xhys-impl</artifactId>
                    <version>1.0-SNAPSHOT</version>
                </dependency>
                <dependency>
                    <groupId>com.yzc</groupId>
                    <artifactId>common-global</artifactId>
                    <version>1.0-SNAPSHOT</version>
                </dependency>
            </dependencies>
        </profile>
        <!-- 淮北矿业部署版本 -->
        <profile>
            <id>hbky</id>
            <properties>
                <profile.active>hbky</profile.active>
            </properties>
            <dependencies>
                <dependency>
                    <groupId>com.yzc</groupId>
                    <artifactId>common-api-hbky-impl</artifactId>
                    <version>1.0-SNAPSHOT</version>
                </dependency>
                <dependency>
                    <groupId>com.yzc</groupId>
                    <artifactId>common-global</artifactId>
                    <version>1.0-SNAPSHOT</version>
                    <exclusions>
                        <exclusion>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-starter-undertow</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                <dependency>
                    <groupId>com.tongweb.springboot</groupId>
                    <artifactId>tongweb-spring-boot-starter-2.x</artifactId>
                    <version>7.0.E.6_P6</version>
                </dependency>
            </dependencies>
        </profile>
        <!-- 北京控股集团部署版本 -->
        <profile>
            <id>bjkg</id>
            <properties>
                <profile.active>bjkg</profile.active>
            </properties>
            <dependencies>
                <dependency>
                    <groupId>com.yzc</groupId>
                    <artifactId>common-api-bjkg-impl</artifactId>
                    <version>1.0-SNAPSHOT</version>
                </dependency>
                <dependency>
                    <groupId>com.yzc</groupId>
                    <artifactId>common-global</artifactId>
                    <version>1.0-SNAPSHOT</version>
                    <!--					<exclusions>-->
                    <!--						<exclusion>-->
                    <!--							<groupId>org.springframework.boot</groupId>-->
                    <!--							<artifactId>spring-boot-starter-undertow</artifactId>-->
                    <!--						</exclusion>-->
                    <!--					</exclusions>-->
                </dependency>
                <!--				<dependency>-->
                <!--					<groupId>com.tongweb.springboot</groupId>-->
                <!--					<artifactId>tongweb-spring-boot-starter-2.x</artifactId>-->
                <!--					<version>7.0.E.6_P6</version>-->
                <!--				</dependency>-->
            </dependencies>
        </profile>

        <!-- 部署版本 -->
        <profile>
            <id>deploy</id>
            <properties>
                <profile.active>deploy</profile.active>
            </properties>
            <dependencies>
                <dependency>
                    <groupId>com.yzc</groupId>
                    <artifactId>common-api-impl</artifactId>
                    <version>1.0-SNAPSHOT</version>
                </dependency>
                <dependency>
                    <groupId>com.yzc</groupId>
                    <artifactId>common-global</artifactId>
                    <version>1.0-SNAPSHOT</version>
                </dependency>
            </dependencies>
        </profile>
    </profiles>

</project>